sudo: required
services:
  - docker

before_install:
  - docker build -t knightbrian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true knightbrian/docker-react npm run test
